version: 2.1
jobs:
  build:
    docker:
     - image: cimg/base:2022.08-22.04
    parallelism: 8
    steps:
      - checkout


      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get -y install python3-pip
            pip3 install -r requirements.txt
            pip3 install -r linters/linter_requirements.txt

      - run:
          name: Tests
          parallel: true
          command: |  
            TESTFILES=$((pytest --co -q --disable-warnings | head -n -2) | circleci tests split --split-by=timings --timings-type=testname)
            mkdir -p test-results
            python3 -m pytest --verbose $TESTFILES --junitxml=test-results/junit.xml
            python3 tests/utils/get_test_names.py
            
      - store_test_results:
          path: test-results

      - run:
          name: Linters
          command: |
            branch=$(python3 linters/get_base_branch.py)
            git diff -U0 origin/${branch} | lint-diffs

      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always

  pypi_publish:
    docker:
        - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |  
            python3 setup.py sdist bdist_wheel
            pip3 install pipenv
            pipenv install twine
            pipenv run twine upload -u __token__ -p $PYPI_TOKEN dist/*
  

workflows:
  workflow:
    jobs:
      - build
      - pypi_publish:
          requires:
            - build
          filters:
            branches:
              only:
                master
