version: 2.1
jobs:
  build:
    docker:
        - image: mariuscristian/numerous:1.0.0

    steps:
      - checkout
      - run:
          name: Tests
          command: |
            python3 -m numerous/pytest
