version: 2.1
jobs:
  build:
    docker:
        - image: mariuscristian/numerous-requirements:1.0.1

    steps:
      - checkout
      - run:
          name: Tests
          command: |
            python3 -m pytest
