version: 2.1
jobs:
  build:
    docker:
        - image: cimg/python:3.9.4

    steps:
      - checkout
      - run:  pip3 install -r requirements.txt
      - run:
          name: Tests
          command: |
            python3 -m pytest

      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always