from abc import ABC, abstractmethod

class ScopeSpecInterface(ABC):
    ...

class ModuleSpecInterface(ABC):
    ...

class ItemsSpecInterface(ABC):
    ...

class ModuleInterface(ABC):
    ...

class ConnectorInterface(ABC):
    ...

class ModuleConnectionsInterface(ABC):
    ...